# /backend/app/src/main/resources/application.yml
spring:
  application:
    name: resume-assistant-backend

  profiles:
    active: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    context-path: /api